package main

import (
	"embed"
	_ "embed"
	"log"
	"log/slog"
	"os"

	"github.com/kyleaupton/flashit/internal/core"
	"github.com/kyleaupton/flashit/internal/drives"
	"github.com/kyleaupton/flashit/internal/eventbus"
	"github.com/kyleaupton/flashit/internal/logger"
	"github.com/kyleaupton/flashit/internal/service"

	"github.com/wailsapp/wails/v3/pkg/application"
)

//go:embed all:frontend/dist
var assets embed.FS

func main() {
	// Check for dry-run mode via environment variable
	if os.Getenv("DRY_RUN") == "1" || os.Getenv("DRY_RUN") == "true" {
		core.DryRun = true
		log.Println("DRY-RUN MODE: Using mock drives, no real disk operations")
		drives.SetProvider(drives.MockProvider{Drives: drives.DefaultMockDrives()})
	}

	app := application.New(application.Options{
		Name:        "FlashIt",
		Description: "Create bootable USB OS installers",
		LogLevel:    slog.LevelInfo,
		Assets: application.AssetOptions{
			Handler: application.AssetFileServerFS(assets),
		},
		Mac: application.MacOptions{
			ApplicationShouldTerminateAfterLastWindowClosed: true,
		},
	})

	// Use Wails' logger for unified log format
	logger.SetLogger(app.Logger)

	// Set global event emitter for backend modules
	eventbus.SetEmitter(func(name string, data any) { app.Event.Emit(name, data) })

	jobsSvc := service.NewJobsService()
	app.RegisterService(application.NewService(jobsSvc))
	drivesSvc := service.NewDrivesService()
	app.RegisterService(application.NewService(drivesSvc))

	// TODO: Add Wails updater service when available in Wails v3
	// See: https://v3alpha.wails.io/guides/distribution/auto-updates
	// The update.json manifest is generated by the release workflow and will
	// be ready when the updater API becomes available.

	app.Window.NewWithOptions(application.WebviewWindowOptions{
		Title:         "FlashIt",
		Width:         800,
		Height:        500,
		DisableResize: true,
		Mac: application.MacWindow{
			InvisibleTitleBarHeight: 50,
			Backdrop:                application.MacBackdropTranslucent,
			TitleBar:                application.MacTitleBarHiddenInset,
		},
		BackgroundColour: application.NewRGB(27, 38, 54),
		URL:              "/",
	})

	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}
