// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService backs the window's ⋯ menu.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function OpenLogFolder(): $CancellablePromise<void> {
    return $Call.ByID(1613443622);
}

/**
 * Quit goes through the same guard as the OS quit: while a job runs, the
 * user is asked first.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(32677315);
}

export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(1819223382);
}
