// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJob cancels a running job by ID.
 * Returns true if the job was found and cancelled, false if not found or already completed.
 */
export function CancelJob(jobID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3452811188, jobID);
}

/**
 * StartJob probes the source, picks the installer by what it found, and
 * refuses a drive the OS does not list as removable before planning.
 */
export function StartJob(req: $models.StartJobRequest): $CancellablePromise<$models.StartJobResponse> {
    return $Call.ByID(2679174400, req).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.StartJobResponse.createFrom;
