// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export class StartJobRequest {
    "SourcePath": string;
    "DriveID": string;

    /** Creates a new StartJobRequest instance. */
    constructor($$source: Partial<StartJobRequest> = {}) {
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("DriveID" in $$source)) {
            this["DriveID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartJobRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartJobRequest($$parsedSource as Partial<StartJobRequest>);
    }
}

export class StartJobResponse {
    "jobId": string;
    "stepInfos": core$0.StepInfo[];

    /** Creates a new StartJobResponse instance. */
    constructor($$source: Partial<StartJobResponse> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("stepInfos" in $$source)) {
            this["stepInfos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): StartJobResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stepInfos" in $$parsedSource) {
            $$parsedSource["stepInfos"] = $$createField1_0($$parsedSource["stepInfos"]);
        }
        return new StartJobResponse($$parsedSource as Partial<StartJobResponse>);
    }
}

export class UpdaterInfo {
    "enabled": boolean;
    "version": string;

    /** Creates a new UpdaterInfo instance. */
    constructor($$source: Partial<UpdaterInfo> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdaterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdaterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdaterInfo($$parsedSource as Partial<UpdaterInfo>);
    }
}

// Private type creation functions
const $$createType0 = core$0.StepInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
