// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * Release is what the update sheet shows of a newer version. Notes is the
 * GitHub release body, Markdown.
 */
export class Release {
    "version": string;
    "name": string;
    "notes": string;
    "publishedAt": string;

    /** Creates a new Release instance. */
    constructor($$source: Partial<Release> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     */
    static createFrom($$source: any = {}): Release {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Release($$parsedSource as Partial<Release>);
    }
}

/**
 * StartJobRequest names the drive by its device path and by what the UI
 * showed of it. Device paths get reused: a stick swapped between two polls
 * takes the old one's path, so the rest must still match.
 */
export class StartJobRequest {
    "SourcePath": string;
    "DriveID": string;
    "SizeBytes": number;
    "Model": string;
    "Serial": string;

    /** Creates a new StartJobRequest instance. */
    constructor($$source: Partial<StartJobRequest> = {}) {
        if (!("SourcePath" in $$source)) {
            this["SourcePath"] = "";
        }
        if (!("DriveID" in $$source)) {
            this["DriveID"] = "";
        }
        if (!("SizeBytes" in $$source)) {
            this["SizeBytes"] = 0;
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Serial" in $$source)) {
            this["Serial"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartJobRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartJobRequest($$parsedSource as Partial<StartJobRequest>);
    }
}

export class StartJobResponse {
    "jobId": string;
    "stepInfos": core$0.StepInfo[];

    /** Creates a new StartJobResponse instance. */
    constructor($$source: Partial<StartJobResponse> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("stepInfos" in $$source)) {
            this["stepInfos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartJobResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): StartJobResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stepInfos" in $$parsedSource) {
            $$parsedSource["stepInfos"] = $$createField1_0($$parsedSource["stepInfos"]);
        }
        return new StartJobResponse($$parsedSource as Partial<StartJobResponse>);
    }
}

export class UpdaterInfo {
    "enabled": boolean;
    "version": string;

    /**
     * State is the updater's phase ("idle", "available", "downloading",
     * "ready", ...) so a page loaded mid-flow can catch up.
     */
    "state": string;
    "pending": Release | null;

    /** Creates a new UpdaterInfo instance. */
    constructor($$source: Partial<UpdaterInfo> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("pending" in $$source)) {
            this["pending"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdaterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdaterInfo {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pending" in $$parsedSource) {
            $$parsedSource["pending"] = $$createField3_0($$parsedSource["pending"]);
        }
        return new UpdaterInfo($$parsedSource as Partial<UpdaterInfo>);
    }
}

// Private type creation functions
const $$createType0 = core$0.StepInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Release.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
