// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PrivService exposes the privileged helper's install state to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * HelperStatus is "ready", "needs-approval" or "not-installed".
 */
export function HelperStatus(): $CancellablePromise<string> {
    return $Call.ByID(4123139748);
}

/**
 * OpenHelperSettings opens the system pane where the user approves the
 * helper. It is a no-op on hosts without one.
 */
export function OpenHelperSettings(): $CancellablePromise<void> {
    return $Call.ByID(495589823);
}
