// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PrivService exposes what the frontend needs from the privileged helper.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenPrivacySettings opens the system pane where the user grants FlashIt
 * access to removable volumes. It is a no-op on hosts without one.
 */
export function OpenPrivacySettings(): $CancellablePromise<void> {
    return $Call.ByID(1755433875);
}
