// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourcesService lets the frontend probe an image before a drive is chosen.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../sources/models.js";

export function Probe(path: string): $CancellablePromise<sources$0.SourceInfo> {
    return $Call.ByID(3999834245, path).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = sources$0.SourceInfo.createFrom;
