// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService is the frontend's view of the updater.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

/**
 * CheckNow checks at once and returns when the check, and on macOS the
 * download, is done.
 */
export function CheckNow(): $CancellablePromise<update$0.State> {
    return $Call.ByID(2774592310).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetState(): $CancellablePromise<update$0.State> {
    return $Call.ByID(1588977015).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenReleasePage opens the page of the version found, built from that
 * version rather than taken from the frontend or the manifest.
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(1434284868);
}

/**
 * Restart installs the ready update and relaunches FlashIt. It is refused
 * while a flash is pending or running.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(583885417);
}

// Private type creation functions
const $$createType0 = update$0.State.createFrom;
