// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdaterService backs the "Check for updates" link.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates opens the updater window, which stays up to say "up to
 * date" when there is nothing newer.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(33187389);
}

export function Info(): $CancellablePromise<$models.UpdaterInfo> {
    return $Call.ByID(2805927110).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdaterInfo.createFrom;
