// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdaterService drives the Wails updater headless; the frontend draws every
 * state from its wails:updater:* events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check asks the release feed for a newer version. It returns nil when
 * this one is the latest.
 */
export function Check(): $CancellablePromise<$models.Release | null> {
    return $Call.ByID(1071699990).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Info(): $CancellablePromise<$models.UpdaterInfo> {
    return $Call.ByID(2805927110).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Install downloads, verifies and stages the release the last Check found.
 * It returns at once; progress and the outcome arrive as updater events.
 */
export function Install(): $CancellablePromise<void> {
    return $Call.ByID(2237814029);
}

/**
 * Restart relaunches into the staged update. It refuses while a job is
 * running, since quitting would leave the drive half written.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(1680076297);
}

// Private type creation functions
const $$createType0 = $models.Release.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UpdaterInfo.createFrom;
