// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * StepInfo provides metadata about a step for UI display
 */
export class StepInfo {
    /**
     * Unique key like "writing-iso", "unmounting-disk"
     */
    "key": string;

    /**
     * Human-readable name like "Writing ISO to USB"
     */
    "name": string;

    /**
     * true for long operations with progress tracking
     */
    "hasProgress": boolean;

    /** Creates a new StepInfo instance. */
    constructor($$source: Partial<StepInfo> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hasProgress" in $$source)) {
            this["hasProgress"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StepInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StepInfo($$parsedSource as Partial<StepInfo>);
    }
}
