// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Kind is the installer family an image belongs to.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LinuxISO = "linux-iso",
    WindowsISO = "windows-iso",
    Unknown = "unknown",
};

/**
 * SourceInfo is what Probe learned about an image. Reason is set only when
 * Kind is Unknown and says why the image cannot be used.
 */
export class SourceInfo {
    "path": string;
    "size": number;
    "kind": Kind;
    "label": string;
    "hybrid": boolean;
    "hasWim": boolean;
    "wimSize": number;
    "reason"?: string;

    /** Creates a new SourceInfo instance. */
    constructor($$source: Partial<SourceInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("hybrid" in $$source)) {
            this["hybrid"] = false;
        }
        if (!("hasWim" in $$source)) {
            this["hasWim"] = false;
        }
        if (!("wimSize" in $$source)) {
            this["wimSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceInfo($$parsedSource as Partial<SourceInfo>);
    }
}
