version: "3"

vars:
  HELPER_NAME: "flashit-helper"
  BUILD_DIR: "../../bin/helpers"

tasks:
  build:
    summary: Build the Linux privileged helper
    cmds:
      - task: clean
      - task: compile
        vars:
          BUILD_FLAGS: '{{.BUILD_FLAGS}}'
          GOOS: '{{.GOOS}}'
          GOARCH: '{{.GOARCH}}'
          CGO_ENABLED: '{{.CGO_ENABLED}}'

  clean:
    summary: Remove old build artifacts
    cmds:
      - rm -f {{.BUILD_DIR}}/{{.HELPER_NAME}}

  compile:
    summary: Compile the helper binary
    env:
      GOOS: '{{.GOOS | default "linux"}}'
      GOARCH: '{{.GOARCH | default ARCH}}'
      CGO_ENABLED: '{{.CGO_ENABLED | default "1"}}'
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build {{.BUILD_FLAGS}} -o {{.BUILD_DIR}}/{{.HELPER_NAME}} .
