// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Mode is what the updater does on this build.
 */
export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Off = "off",
    Notify = "notify",
    Install = "install",
};

/**
 * State is what the frontend renders. Version and Notes come from the
 * unsigned manifest; Version is checked to be a plain release version, and
 * ReleaseURL is built from it here rather than taken from the manifest.
 */
export class State {
    "mode": Mode;
    "status": Status;
    "current": string;
    "version"?: string;
    "notes"?: string;
    "releaseUrl"?: string;
    "error"?: string;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new State($$parsedSource as Partial<State>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusIdle = "idle",
    StatusChecking = "checking",
    StatusUpToDate = "up-to-date",
    StatusAvailable = "available",
    StatusDownloading = "downloading",
    StatusReady = "ready",
    StatusRestarting = "restarting",
    StatusError = "error",
};
